name: Bump Nuget package version
on:
  push:
    branches:
      - asdf

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x' # or 8.0.x / 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Bump build version
        id: bump
        uses: vers-one/dotnet-project-version-updater@v1.7
        with:
          file: "Souchy.Net/Souchy.Net.csproj"
          version: bump-build

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add .
          git commit -m "Bump project version to ${{ steps.bump.outputs.newVersion }}"
          git tag v${{ steps.bump.outputs.newVersion }}
          git push origin HEAD --tags
