name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x' # or 8.0.x / 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Bump build version
        id: bump
        uses: vers-one/dotnet-project-version-updater@v1.7
        with:
          file: "Souchy.Net/Souchy.Net.csproj"
          version: bump-build

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal

#       - name: Set version from Git tag
#         run: echo "GIT_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

#       - name: Generate version
#         run: echo "PKG_VERSION=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Pack
        run: dotnet pack --configuration Release --no-build -o out # /p:PackageVersion=${{ env.GIT_VERSION }}-${{ env.PKG_VERSION }}

      - name: Push to NuGet
        run: dotnet nuget push "out/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
