name: Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x' # or 8.0.x / 9.0.x

      - name: Restore dependencies
        run: dotnet restore Souchy.Net/Souchy.Net.csproj

      - name: Build
        run: dotnet build Souchy.Net/Souchy.Net.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test Souchy.Net/Souchy.Net.csproj --configuration Release --no-build --verbosity normal

      - name: Pack
        run: dotnet pack Souchy.Net/Souchy.Net.csproj --configuration Release --no-build -o out

      - name: Push to NuGet
        run: dotnet nuget push "out/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
